version: "3.8"
services:
    "toneye":
        image: insyscompany/toneye:release
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: toneye
        restart: always
        ports:
            - 8080:80
            - 8443:443
        logging:
            options:
                max-size: 50m