version: "3.8"
services:
    "toneye":
        image: insyscompany/toneye:release
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                - BUILD_CONFIG=prod-kor
        container_name: toneye
        restart: always
        ports:
            - 8080:80
            - 8443:443
        logging:
            options:
                max-size: 50m
    "toneye-english":
        image: insyscompany/toneye:release-english
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: toneye-english
        restart: always
        ports:
            - 8080:80
            - 8443:443
        logging:
            options:
                max-size: 50m